# -*- coding: utf-8 -*-
"""topsis_text_classification

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ygizG63mHqNNUEv2gWDiF691SYlB5m2G
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

def normalizeMatrix(dataMatrix):
    squaredSum = np.sqrt((dataMatrix ** 2).sum(axis=0))
    return dataMatrix / squaredSum

def calculateTopsis(inputFile, weights, impacts):
    dataSet = pd.read_csv(inputFile)
    modelNames = dataSet.iloc[:, 0]
    numericData = dataSet.iloc[:, 1:].values.astype(float)

    normalizedData = normalizeMatrix(numericData)

    weightedData = normalizedData * weights

    idealBest = []
    idealWorst = []

    for i in range(len(impacts)):
        if impacts[i] == '+':
            idealBest.append(max(weightedData[:, i]))
            idealWorst.append(min(weightedData[:, i]))
        else:
            idealBest.append(min(weightedData[:, i]))
            idealWorst.append(max(weightedData[:, i]))

    idealBest = np.array(idealBest)
    idealWorst = np.array(idealWorst)

    distanceBest = np.sqrt(((weightedData - idealBest) ** 2).sum(axis=1))
    distanceWorst = np.sqrt(((weightedData - idealWorst) ** 2).sum(axis=1))

    performanceScore = distanceWorst / (distanceBest + distanceWorst)

    dataSet['Topsis Score'] = performanceScore
    dataSet['Rank'] = dataSet['Topsis Score'].rank(ascending=False)

    return dataSet

def generateVisuals(resultData):
    plt.figure(figsize=(10, 6))
    plt.bar(resultData.iloc[:, 0], resultData['Topsis Score'], color='skyblue')
    plt.xlabel('Models')
    plt.ylabel('Topsis Score')
    plt.title('Model Ranking Using Topsis')
    plt.savefig('result_graph.png')
    plt.show()

data = {
    'Model': ['BERT-Base', 'RoBERTa', 'DistilBERT', 'XLNet', 'MobileBERT'],
    'Accuracy': [0.92, 0.94, 0.89, 0.93, 0.88],
    'F1Score': [0.91, 0.93, 0.88, 0.92, 0.87],
    'InferenceTime_ms': [120, 140, 60, 150, 45],
    'ModelSize_MB': [440, 500, 260, 550, 100]
}

df = pd.DataFrame(data)
df.to_csv('model_data.csv', index=False)

weights = [1, 1, 1, 1]
impacts = ['+', '+', '-', '-']

results = calculateTopsis('model_data.csv', weights, impacts)

results.to_csv('result_data.csv', index=False)
generateVisuals(results)
print(results)

